//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Autoheal) DeepCopyInto(out *Autoheal) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Autoheal.
func (in *Autoheal) DeepCopy() *Autoheal {
	if in == nil {
		return nil
	}
	out := new(Autoheal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Autoheal) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutohealConfig) DeepCopyInto(out *AutohealConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutohealConfig.
func (in *AutohealConfig) DeepCopy() *AutohealConfig {
	if in == nil {
		return nil
	}
	out := new(AutohealConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutohealConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutohealConfigList) DeepCopyInto(out *AutohealConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AutohealConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutohealConfigList.
func (in *AutohealConfigList) DeepCopy() *AutohealConfigList {
	if in == nil {
		return nil
	}
	out := new(AutohealConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutohealConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutohealConfigScenario) DeepCopyInto(out *AutohealConfigScenario) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutohealConfigScenario.
func (in *AutohealConfigScenario) DeepCopy() *AutohealConfigScenario {
	if in == nil {
		return nil
	}
	out := new(AutohealConfigScenario)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutohealConfigSpec) DeepCopyInto(out *AutohealConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutohealConfigSpec.
func (in *AutohealConfigSpec) DeepCopy() *AutohealConfigSpec {
	if in == nil {
		return nil
	}
	out := new(AutohealConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutohealConfigStatus) DeepCopyInto(out *AutohealConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutohealConfigStatus.
func (in *AutohealConfigStatus) DeepCopy() *AutohealConfigStatus {
	if in == nil {
		return nil
	}
	out := new(AutohealConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutohealConfigTree) DeepCopyInto(out *AutohealConfigTree) {
	*out = *in
	if in.Tree != nil {
		in, out := &in.Tree, &out.Tree
		*out = make([]AutohealConfigTreeResponse, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutohealConfigTree.
func (in *AutohealConfigTree) DeepCopy() *AutohealConfigTree {
	if in == nil {
		return nil
	}
	out := new(AutohealConfigTree)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutohealConfigTreeResponse) DeepCopyInto(out *AutohealConfigTreeResponse) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutohealConfigTreeResponse.
func (in *AutohealConfigTreeResponse) DeepCopy() *AutohealConfigTreeResponse {
	if in == nil {
		return nil
	}
	out := new(AutohealConfigTreeResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutohealList) DeepCopyInto(out *AutohealList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Autoheal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutohealList.
func (in *AutohealList) DeepCopy() *AutohealList {
	if in == nil {
		return nil
	}
	out := new(AutohealList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutohealList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutohealSpec) DeepCopyInto(out *AutohealSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutohealSpec.
func (in *AutohealSpec) DeepCopy() *AutohealSpec {
	if in == nil {
		return nil
	}
	out := new(AutohealSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutohealStatus) DeepCopyInto(out *AutohealStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutohealStatus.
func (in *AutohealStatus) DeepCopy() *AutohealStatus {
	if in == nil {
		return nil
	}
	out := new(AutohealStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigRepositoryInfo) DeepCopyInto(out *ConfigRepositoryInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigRepositoryInfo.
func (in *ConfigRepositoryInfo) DeepCopy() *ConfigRepositoryInfo {
	if in == nil {
		return nil
	}
	out := new(ConfigRepositoryInfo)
	in.DeepCopyInto(out)
	return out
}
